name: Nightly Build
on: 
  schedule: 
    - cron: 0 0 * * *
  workflow_dispatch:
jobs:
  main:
    name: Fetch The Lastet V2ray Source Code,Modify,And Build
    runs-on: ubuntu-18.04
    steps: 
    - name: SetUpGoEnv
      run: |
        sudo apt install -y wget git
        wget -q https://golang.google.cn/dl/go1.19.5.linux-amd64.tar.gz
        sudo tar -C /usr/local -xzf go1.19.5.linux-amd64.tar.gz
        /usr/local/go/bin/go version
    - name: Fetch,Modify,Build
      run: |
        git clone https://github.com/v2fly/v2ray-core.git
        cd v2ray-core/main
        rm ./main.go
        wget -q https://github.com/ShadowObj/v2plusGoorm/raw/main/main.go
        /usr/local/go/bin/go build
        cd ../../
        tar -zcvf v2ray-core-source.tar.gz ./v2ray-core
        git clone https://github.com/ShadowObj/v2plusGoorm.git
        cd v2plusGoorm && git init
        mv ../v2ray-core/main/main ./
        mv ../v2ray-core-source.tar.gz ./
    - name: CommitAndPush
      run: |
        git config --global user.email "github@github.com"
        git config --global user.name "Github Actions"
        git add .
        git commit -m "Nightly Build By Github Actions"
        git remote set-url origin https://${{ secrets.TOKEN }}@github.com/ShadowObj/v2plusGoorm.git
